---
abstract: 'Utility for accessing remote servers via SSH'
author:
  - 'Dominic Humphries <dominic@oneandoneis2.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v0.9.1, Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Goto
requires:
  Config::Tiny: 0
  Moo: 0
  perl: v5.12.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/oneandoneis2/App-Goto/issues
  homepage: https://github.com/oneandoneis2/App-Goto
  repository: https://github.com/oneandoneis2/App-Goto.git
version: 0.07
